//! Server-info DTOs — GET /actuator/info and GET /api/v1/libraries.
//!
//! Contract: specs/openapi/komga-openapi.yaml (snapshot endpoints);
//! shared fixtures: specs/contracts/fixtures/connection/.
//!
//! `ServerInfo` is deliberately tolerant: Spring Boot build-info/git blocks
//! may be absent or contain extra fields (unknown fields are ignored).

use serde::{Deserialize, Serialize};

/// `GET /actuator/info` — the snapshot-sanctioned "Get server information".
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct ServerInfo {
    pub build: Option<BuildInfo>,
    pub git: Option<GitInfo>,
}

/// Spring Boot build-info block (generated by the `build-info` goal).
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct BuildInfo {
    pub artifact: Option<String>,
    pub name: Option<String>,
    pub time: Option<String>,
    pub version: Option<String>,
    pub group: Option<String>,
}

/// Spring Boot git block (git.properties).
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct GitInfo {
    pub branch: Option<String>,
    pub commit: Option<GitCommit>,
}

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct GitCommit {
    pub id: Option<String>,
    pub time: Option<String>,
}

/// Minimal LibraryDto (`GET /api/v1/libraries`, plain array).
/// Unknown fields (scan flags, import flags, ...) are ignored by serde.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Library {
    pub id: String,
    pub name: String,
    pub root: String,
    #[serde(default)]
    pub unavailable: Option<bool>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decoder_server_info_fixture() {
        let json =
            include_str!("../../../../specs/contracts/fixtures/connection/actuator-info.json");
        let info: ServerInfo = serde_json::from_str(json).expect("shared fixture must decode");
        assert_eq!(
            info.build.as_ref().unwrap().version.as_deref(),
            Some("1.26.3")
        );
        assert_eq!(
            info.build.as_ref().unwrap().artifact.as_deref(),
            Some("komga")
        );
        assert_eq!(
            info.git
                .as_ref()
                .unwrap()
                .commit
                .as_ref()
                .unwrap()
                .id
                .as_deref(),
            Some("e93fa2a")
        );
    }

    #[test]
    fn decoder_libraries_fixture() {
        let json = include_str!("../../../../specs/contracts/fixtures/connection/libraries.json");
        let libraries: Vec<Library> =
            serde_json::from_str(json).expect("shared fixture must decode");
        assert_eq!(libraries.len(), 2);
        assert_eq!(libraries[0].name, "Manga");
        assert_eq!(libraries[0].root, "/mnt/media/manga");
        assert_eq!(libraries[0].unavailable, Some(false));
    }

    #[test]
    fn tolerates_empty_and_partial_bodies() {
        let info: ServerInfo = serde_json::from_str("{}").unwrap();
        assert_eq!(info, ServerInfo::default());

        let info: ServerInfo =
            serde_json::from_str(r#"{"build":{"version":"1.26.3"},"extra":42}"#).unwrap();
        assert_eq!(info.build.unwrap().version.as_deref(), Some("1.26.3"));
    }
}
