// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One captured line.
class LogRecord {
  /// `error` | `warn` | `info` | `debug` | `trace`.
  final String level;

  /// The `log` target, i.e. the module that wrote it.
  final String target;
  final String message;

  /// Wall clock when the record was pushed, RFC 3339 with milliseconds.
  final String at;

  const LogRecord({
    required this.level,
    required this.target,
    required this.message,
    required this.at,
  });

  @override
  int get hashCode =>
      level.hashCode ^ target.hashCode ^ message.hashCode ^ at.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogRecord &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          target == other.target &&
          message == other.message &&
          at == other.at;
}

/// Counters and the one number that decides whether any of this is real.
class LogStats {
  /// False when some other logger already owned the global slot, in which
  /// case every other field here describes a ring nobody writes to. Reported
  /// rather than assumed because that is a state the UI has to be able to see.
  final bool installed;
  final PlatformInt64 capacity;

  /// Records currently held.
  final PlatformInt64 retained;

  /// Records evicted because the ring was full.
  final PlatformInt64 dropped;
  final PlatformInt64 errors;
  final PlatformInt64 warnings;
  final PlatformInt64 info;
  final PlatformInt64 debug;
  final PlatformInt64 trace;

  /// The newest error line, if one was ever captured.
  final String? lastError;

  /// The level filter the ring installed, as a name. `off` means it installed
  /// nothing because a platform had already picked a level.
  final String maxLevel;

  const LogStats({
    required this.installed,
    required this.capacity,
    required this.retained,
    required this.dropped,
    required this.errors,
    required this.warnings,
    required this.info,
    required this.debug,
    required this.trace,
    this.lastError,
    required this.maxLevel,
  });

  @override
  int get hashCode =>
      installed.hashCode ^
      capacity.hashCode ^
      retained.hashCode ^
      dropped.hashCode ^
      errors.hashCode ^
      warnings.hashCode ^
      info.hashCode ^
      debug.hashCode ^
      trace.hashCode ^
      lastError.hashCode ^
      maxLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogStats &&
          runtimeType == other.runtimeType &&
          installed == other.installed &&
          capacity == other.capacity &&
          retained == other.retained &&
          dropped == other.dropped &&
          errors == other.errors &&
          warnings == other.warnings &&
          info == other.info &&
          debug == other.debug &&
          trace == other.trace &&
          lastError == other.lastError &&
          maxLevel == other.maxLevel;
}
