// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The pragmas that decide whether this connection is the one the store was
/// configured to open, plus the mirror's size per table.
class DbHealth {
  /// `PRAGMA user_version`, i.e. the schema the migrations left behind.
  final PlatformInt64 schemaVersion;

  /// `"ok"`, or the first complaint from `PRAGMA integrity_check`.
  final String integrity;
  final String journalMode;
  final PlatformInt64 pageSize;
  final PlatformInt64 pageCount;

  /// Pages held on the free list — the file's own record of reusable space.
  final PlatformInt64 freelistCount;
  final PlatformInt64 busyTimeoutMs;
  final bool foreignKeysOn;

  /// Bytes in the main database file, from `page_size * page_count`. The
  /// `-wal` and `-shm` siblings are deliberately not counted: their size
  /// depends on when the last checkpoint ran, which is not a fact about the
  /// data.
  final PlatformInt64 fileBytes;

  /// Every user table and how full it is, in name order.
  final List<TableRows> tables;

  const DbHealth({
    required this.schemaVersion,
    required this.integrity,
    required this.journalMode,
    required this.pageSize,
    required this.pageCount,
    required this.freelistCount,
    required this.busyTimeoutMs,
    required this.foreignKeysOn,
    required this.fileBytes,
    required this.tables,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      integrity.hashCode ^
      journalMode.hashCode ^
      pageSize.hashCode ^
      pageCount.hashCode ^
      freelistCount.hashCode ^
      busyTimeoutMs.hashCode ^
      foreignKeysOn.hashCode ^
      fileBytes.hashCode ^
      tables.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbHealth &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          integrity == other.integrity &&
          journalMode == other.journalMode &&
          pageSize == other.pageSize &&
          pageCount == other.pageCount &&
          freelistCount == other.freelistCount &&
          busyTimeoutMs == other.busyTimeoutMs &&
          foreignKeysOn == other.foreignKeysOn &&
          fileBytes == other.fileBytes &&
          tables == other.tables;
}

/// Row count for one table.
class TableRows {
  final String table;
  final PlatformInt64 rows;

  const TableRows({
    required this.table,
    required this.rows,
  });

  @override
  int get hashCode => table.hashCode ^ rows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableRows &&
          runtimeType == other.runtimeType &&
          table == other.table &&
          rows == other.rows;
}
