import Foundation

/// `GET /actuator/info` — the OpenAPI snapshot's "Get server information"
/// endpoint (Spring Boot build-info + git blocks). Tolerant: any block may
/// be absent; unknown fields are ignored by the decoder.
public struct ServerInfoDTO: Decodable, Sendable, Equatable {
    public let build: BuildInfoDTO?
    public let git: GitInfoDTO?

    public init(build: BuildInfoDTO? = nil, git: GitInfoDTO? = nil) {
        self.build = build
        self.git = git
    }
}

/// Spring Boot build-info block (generated by the `build-info` goal).
public struct BuildInfoDTO: Decodable, Sendable, Equatable {
    public let artifact: String?
    public let name: String?
    public let time: String?
    public let version: String?
    public let group: String?

    public init(artifact: String? = nil, name: String? = nil, time: String? = nil, version: String? = nil, group: String? = nil) {
        self.artifact = artifact
        self.name = name
        self.time = time
        self.version = version
        self.group = group
    }
}

/// Spring Boot git block (git.properties).
public struct GitInfoDTO: Decodable, Sendable, Equatable {
    public let branch: String?
    public let commit: GitCommitDTO?

    public init(branch: String? = nil, commit: GitCommitDTO? = nil) {
        self.branch = branch
        self.commit = commit
    }
}

public struct GitCommitDTO: Decodable, Sendable, Equatable {
    public let id: String?
    public let time: String?

    public init(id: String? = nil, time: String? = nil) {
        self.id = id
        self.time = time
    }
}

/// Minimal LibraryDto (`GET /api/v1/libraries`, plain array).
/// The snapshot requires many scan/import flags; unknown fields are ignored.
public struct LibraryDTO: Decodable, Sendable, Equatable, Identifiable {
    public let id: String
    public let name: String
    public let root: String
    public let unavailable: Bool?

    public init(id: String, name: String, root: String, unavailable: Bool? = nil) {
        self.id = id
        self.name = name
        self.root = root
        self.unavailable = unavailable
    }
}