// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Result of a bootstrap run (Phase 0 mirrors the first page only).
class BootstrapSummary {
  final String serverId;
  final BigInt syncedSeries;
  final PlatformInt64 totalElements;
  final bool hasMorePages;

  const BootstrapSummary({
    required this.serverId,
    required this.syncedSeries,
    required this.totalElements,
    required this.hasMorePages,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      syncedSeries.hashCode ^
      totalElements.hashCode ^
      hasMorePages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BootstrapSummary &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          syncedSeries == other.syncedSeries &&
          totalElements == other.totalElements &&
          hasMorePages == other.hasMorePages;
}
