// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// What one reconciliation pass did.
class ReconcileSummary {
  final String serverId;
  final String trigger;
  final BigInt seriesUpserted;
  final BigInt seriesAdded;
  final BigInt seriesChanged;
  final BigInt seriesRemoved;
  final BigInt booksUpserted;
  final BigInt booksAdded;
  final BigInt booksChanged;
  final BigInt booksRemoved;
  final BigInt collectionsUpserted;
  final BigInt collectionsAdded;
  final BigInt collectionsChanged;
  final BigInt collectionsRemoved;
  final BigInt readlistsUpserted;
  final BigInt readlistsAdded;
  final BigInt readlistsChanged;
  final BigInt readlistsRemoved;
  final BigInt librariesUpserted;
  final BigInt librariesRemoved;
  final BigInt readProgress;
  final int pagesSwept;

  /// Cover file paths orphaned by delete propagation (the facade removes
  /// them from disk; the SQLite records are already gone).
  final List<String> orphanedCovers;

  /// True when the mirror already matched the server and nothing changed.
  final bool clean;

  const ReconcileSummary({
    required this.serverId,
    required this.trigger,
    required this.seriesUpserted,
    required this.seriesAdded,
    required this.seriesChanged,
    required this.seriesRemoved,
    required this.booksUpserted,
    required this.booksAdded,
    required this.booksChanged,
    required this.booksRemoved,
    required this.collectionsUpserted,
    required this.collectionsAdded,
    required this.collectionsChanged,
    required this.collectionsRemoved,
    required this.readlistsUpserted,
    required this.readlistsAdded,
    required this.readlistsChanged,
    required this.readlistsRemoved,
    required this.librariesUpserted,
    required this.librariesRemoved,
    required this.readProgress,
    required this.pagesSwept,
    required this.orphanedCovers,
    required this.clean,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      trigger.hashCode ^
      seriesUpserted.hashCode ^
      seriesAdded.hashCode ^
      seriesChanged.hashCode ^
      seriesRemoved.hashCode ^
      booksUpserted.hashCode ^
      booksAdded.hashCode ^
      booksChanged.hashCode ^
      booksRemoved.hashCode ^
      collectionsUpserted.hashCode ^
      collectionsAdded.hashCode ^
      collectionsChanged.hashCode ^
      collectionsRemoved.hashCode ^
      readlistsUpserted.hashCode ^
      readlistsAdded.hashCode ^
      readlistsChanged.hashCode ^
      readlistsRemoved.hashCode ^
      librariesUpserted.hashCode ^
      librariesRemoved.hashCode ^
      readProgress.hashCode ^
      pagesSwept.hashCode ^
      orphanedCovers.hashCode ^
      clean.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReconcileSummary &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          trigger == other.trigger &&
          seriesUpserted == other.seriesUpserted &&
          seriesAdded == other.seriesAdded &&
          seriesChanged == other.seriesChanged &&
          seriesRemoved == other.seriesRemoved &&
          booksUpserted == other.booksUpserted &&
          booksAdded == other.booksAdded &&
          booksChanged == other.booksChanged &&
          booksRemoved == other.booksRemoved &&
          collectionsUpserted == other.collectionsUpserted &&
          collectionsAdded == other.collectionsAdded &&
          collectionsChanged == other.collectionsChanged &&
          collectionsRemoved == other.collectionsRemoved &&
          readlistsUpserted == other.readlistsUpserted &&
          readlistsAdded == other.readlistsAdded &&
          readlistsChanged == other.readlistsChanged &&
          readlistsRemoved == other.readlistsRemoved &&
          librariesUpserted == other.librariesUpserted &&
          librariesRemoved == other.librariesRemoved &&
          readProgress == other.readProgress &&
          pagesSwept == other.pagesSwept &&
          orphanedCovers == other.orphanedCovers &&
          clean == other.clean;
}
