import java.util.Properties

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

// Release signing material (generated by scripts/android_release_key.sh — never
// commit the .jks or this file's secrets; android/app/android/.gitignore covers
// both). Falling back to debug signing would make every release a different
// identity than the previous one, so release upgrades could not overwrite
// installs: keep the same key for the life of applicationId dev.sakurasep.comic.
val keystoreProperties = Properties().apply {
    val f = rootProject.file("key.properties")
    if (f.exists()) f.inputStream().use { load(it) }
}
val releaseKeyStoreFile = keystoreProperties.getProperty("storeFile")
    ?.let { rootProject.file(it) }
    ?.takeIf { it.exists() }

android {
    // Stable applicationId, fixed at first install: changing it later forces a
    // reinstall and wipes the local SQLite mirror and downloaded books.
    namespace = "dev.sakurasep.comic"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    defaultConfig {
        applicationId = "dev.sakurasep.comic"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    signingConfigs {
        if (releaseKeyStoreFile != null) {
            create("release") {
                storeFile = releaseKeyStoreFile
                storePassword = keystoreProperties.getProperty("storePassword")
                keyAlias = keystoreProperties.getProperty("keyAlias")
                keyPassword = keystoreProperties.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        release {
            // Self-signed release key when scripts/android_release_key.sh has
            // run; without it the build fails loudly rather than silently
            // shipping unsigned or under the debug identity.
            signingConfig = signingConfigs.findByName("release")
                ?: error(
                    "release signing is not configured — run " +
                        "scripts/android_release_key.sh first"
                )
        }
    }
}

flutter {
    source = "../.."
}
