// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Locally stored book row (read progress comes from a LEFT JOIN so the
/// book list and read-status filters read one table set).
class BookRow {
  final String serverId;
  final String remoteId;
  final String seriesId;
  final String? seriesTitle;
  final String title;
  final String? number;
  final double? numberSort;
  final PlatformInt64? fileSize;
  final String? mediaType;
  final PlatformInt64? pagesCount;
  final String? createdAt;
  final String? lastModified;
  final PlatformInt64? progressPage;
  final bool progressCompleted;

  /// FTS rowid (incremental search-index updates); internal.
  final PlatformInt64? ftsRowid;

  const BookRow({
    required this.serverId,
    required this.remoteId,
    required this.seriesId,
    this.seriesTitle,
    required this.title,
    this.number,
    this.numberSort,
    this.fileSize,
    this.mediaType,
    this.pagesCount,
    this.createdAt,
    this.lastModified,
    this.progressPage,
    required this.progressCompleted,
    this.ftsRowid,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      remoteId.hashCode ^
      seriesId.hashCode ^
      seriesTitle.hashCode ^
      title.hashCode ^
      number.hashCode ^
      numberSort.hashCode ^
      fileSize.hashCode ^
      mediaType.hashCode ^
      pagesCount.hashCode ^
      createdAt.hashCode ^
      lastModified.hashCode ^
      progressPage.hashCode ^
      progressCompleted.hashCode ^
      ftsRowid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookRow &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          remoteId == other.remoteId &&
          seriesId == other.seriesId &&
          seriesTitle == other.seriesTitle &&
          title == other.title &&
          number == other.number &&
          numberSort == other.numberSort &&
          fileSize == other.fileSize &&
          mediaType == other.mediaType &&
          pagesCount == other.pagesCount &&
          createdAt == other.createdAt &&
          lastModified == other.lastModified &&
          progressPage == other.progressPage &&
          progressCompleted == other.progressCompleted &&
          ftsRowid == other.ftsRowid;
}
