// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Locally stored collection row.
class CollectionRow {
  final String serverId;
  final String remoteId;
  final String name;
  final bool ordered;
  final bool filtered;
  final String? createdDate;
  final String? lastModifiedDate;

  const CollectionRow({
    required this.serverId,
    required this.remoteId,
    required this.name,
    required this.ordered,
    required this.filtered,
    this.createdDate,
    this.lastModifiedDate,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      remoteId.hashCode ^
      name.hashCode ^
      ordered.hashCode ^
      filtered.hashCode ^
      createdDate.hashCode ^
      lastModifiedDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectionRow &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          remoteId == other.remoteId &&
          name == other.name &&
          ordered == other.ordered &&
          filtered == other.filtered &&
          createdDate == other.createdDate &&
          lastModifiedDate == other.lastModifiedDate;
}
