// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One tombstone row.
class Tombstone {
  final String serverId;
  final String entityType;
  final String remoteId;
  final String deletedAt;
  final String cause;

  const Tombstone({
    required this.serverId,
    required this.entityType,
    required this.remoteId,
    required this.deletedAt,
    required this.cause,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      entityType.hashCode ^
      remoteId.hashCode ^
      deletedAt.hashCode ^
      cause.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tombstone &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          entityType == other.entityType &&
          remoteId == other.remoteId &&
          deletedAt == other.deletedAt &&
          cause == other.cause;
}
