// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'books.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'series.dart';

class BookPageResult {
  final List<BookRow> items;
  final PlatformInt64 total;

  const BookPageResult({
    required this.items,
    required this.total,
  });

  @override
  int get hashCode => items.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookPageResult &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total;
}

/// One library row with its local counts (Library 列表/详情).
class LibraryCountRow {
  final String remoteId;
  final String name;
  final String? root;
  final bool unavailable;
  final PlatformInt64 seriesCount;
  final PlatformInt64 bookCount;
  final PlatformInt64 readCount;

  const LibraryCountRow({
    required this.remoteId,
    required this.name,
    this.root,
    required this.unavailable,
    required this.seriesCount,
    required this.bookCount,
    required this.readCount,
  });

  @override
  int get hashCode =>
      remoteId.hashCode ^
      name.hashCode ^
      root.hashCode ^
      unavailable.hashCode ^
      seriesCount.hashCode ^
      bookCount.hashCode ^
      readCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryCountRow &&
          runtimeType == other.runtimeType &&
          remoteId == other.remoteId &&
          name == other.name &&
          root == other.root &&
          unavailable == other.unavailable &&
          seriesCount == other.seriesCount &&
          bookCount == other.bookCount &&
          readCount == other.readCount;
}

/// One flat row for the FFI: the read target plus the series facts the UI needs
/// to draw it honestly ("no next book" vs "we cannot prove there is no next
/// book" are different sentences, so the completeness flag travels with it).
class ReadTargetRow {
  final BookRow book;
  final String intent;

  /// 1-based position in [`ordered_books`]; 0 when there is no target.
  final PlatformInt64 position;
  final PlatformInt64? bookCount;
  final bool complete;

  const ReadTargetRow({
    required this.book,
    required this.intent,
    required this.position,
    this.bookCount,
    required this.complete,
  });

  @override
  int get hashCode =>
      book.hashCode ^
      intent.hashCode ^
      position.hashCode ^
      bookCount.hashCode ^
      complete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadTargetRow &&
          runtimeType == other.runtimeType &&
          book == other.book &&
          intent == other.intent &&
          position == other.position &&
          bookCount == other.bookCount &&
          complete == other.complete;
}

class SeriesPageResult {
  final List<SeriesRow> items;
  final PlatformInt64 total;

  const SeriesPageResult({
    required this.items,
    required this.total,
  });

  @override
  int get hashCode => items.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeriesPageResult &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total;
}
