// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The continue-reading shelf: books read partially (page > 0, not
/// completed), newest local activity first. 断开网络后依旧可用：
/// 完全由 read_progress + books 本地查询构成。
class ContinueReadingRow {
  final String bookId;
  final String bookTitle;
  final String? number;
  final String seriesId;
  final String seriesName;
  final PlatformInt64? page;
  final PlatformInt64? totalPages;

  /// Progress 0–100 when total pages are known (UI progress bar).
  final PlatformInt64? progressPct;
  final String? localUpdatedAt;

  const ContinueReadingRow({
    required this.bookId,
    required this.bookTitle,
    this.number,
    required this.seriesId,
    required this.seriesName,
    this.page,
    this.totalPages,
    this.progressPct,
    this.localUpdatedAt,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      bookTitle.hashCode ^
      number.hashCode ^
      seriesId.hashCode ^
      seriesName.hashCode ^
      page.hashCode ^
      totalPages.hashCode ^
      progressPct.hashCode ^
      localUpdatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContinueReadingRow &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          bookTitle == other.bookTitle &&
          number == other.number &&
          seriesId == other.seriesId &&
          seriesName == other.seriesName &&
          page == other.page &&
          totalPages == other.totalPages &&
          progressPct == other.progressPct &&
          localUpdatedAt == other.localUpdatedAt;
}
