// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Locally stored series row (mirrors the remote SeriesDto subset).
class SeriesRow {
  final String serverId;
  final String remoteId;
  final String libraryId;
  final String name;
  final String? sortName;
  final String? status;
  final String? createdAt;
  final String? lastModified;
  final PlatformInt64? booksCount;
  final PlatformInt64? booksReadCount;
  final PlatformInt64? booksUnreadCount;
  final PlatformInt64? booksInProgressCount;

  /// FTS rowid (incremental search-index updates); internal.
  final PlatformInt64? ftsRowid;

  const SeriesRow({
    required this.serverId,
    required this.remoteId,
    required this.libraryId,
    required this.name,
    this.sortName,
    this.status,
    this.createdAt,
    this.lastModified,
    this.booksCount,
    this.booksReadCount,
    this.booksUnreadCount,
    this.booksInProgressCount,
    this.ftsRowid,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      remoteId.hashCode ^
      libraryId.hashCode ^
      name.hashCode ^
      sortName.hashCode ^
      status.hashCode ^
      createdAt.hashCode ^
      lastModified.hashCode ^
      booksCount.hashCode ^
      booksReadCount.hashCode ^
      booksUnreadCount.hashCode ^
      booksInProgressCount.hashCode ^
      ftsRowid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeriesRow &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          remoteId == other.remoteId &&
          libraryId == other.libraryId &&
          name == other.name &&
          sortName == other.sortName &&
          status == other.status &&
          createdAt == other.createdAt &&
          lastModified == other.lastModified &&
          booksCount == other.booksCount &&
          booksReadCount == other.booksReadCount &&
          booksUnreadCount == other.booksUnreadCount &&
          booksInProgressCount == other.booksInProgressCount &&
          ftsRowid == other.ftsRowid;
}
