// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Locally stored series row (subset of the remote SeriesDto).
class SeriesRow {
  final String serverId;
  final String remoteId;
  final String libraryId;
  final String name;
  final String? sortName;
  final String? status;
  final String? createdAt;
  final String? lastModified;

  const SeriesRow({
    required this.serverId,
    required this.remoteId,
    required this.libraryId,
    required this.name,
    this.sortName,
    this.status,
    this.createdAt,
    this.lastModified,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      remoteId.hashCode ^
      libraryId.hashCode ^
      name.hashCode ^
      sortName.hashCode ^
      status.hashCode ^
      createdAt.hashCode ^
      lastModified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeriesRow &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          remoteId == other.remoteId &&
          libraryId == other.libraryId &&
          name == other.name &&
          sortName == other.sortName &&
          status == other.status &&
          createdAt == other.createdAt &&
          lastModified == other.lastModified;
}
