// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One `sync_state` row.
class EntitySyncState {
  final String serverId;
  final String entityType;
  final String? lastSyncAt;
  final String? syncCursor;
  final String syncStatus;
  final String? lastError;
  final String? lastFullSync;
  final String? lastSuccessfulSync;

  const EntitySyncState({
    required this.serverId,
    required this.entityType,
    this.lastSyncAt,
    this.syncCursor,
    required this.syncStatus,
    this.lastError,
    this.lastFullSync,
    this.lastSuccessfulSync,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      entityType.hashCode ^
      lastSyncAt.hashCode ^
      syncCursor.hashCode ^
      syncStatus.hashCode ^
      lastError.hashCode ^
      lastFullSync.hashCode ^
      lastSuccessfulSync.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntitySyncState &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          entityType == other.entityType &&
          lastSyncAt == other.lastSyncAt &&
          syncCursor == other.syncCursor &&
          syncStatus == other.syncStatus &&
          lastError == other.lastError &&
          lastFullSync == other.lastFullSync &&
          lastSuccessfulSync == other.lastSuccessfulSync;
}
