// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A `thumbnails` row: logical thumbnail -> local file path.
class ThumbnailRow {
  final String serverId;
  final String remoteId;
  final String variant;
  final String localPath;
  final PlatformInt64 sizeBytes;
  final String lastAccess;

  const ThumbnailRow({
    required this.serverId,
    required this.remoteId,
    required this.variant,
    required this.localPath,
    required this.sizeBytes,
    required this.lastAccess,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      remoteId.hashCode ^
      variant.hashCode ^
      localPath.hashCode ^
      sizeBytes.hashCode ^
      lastAccess.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThumbnailRow &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          remoteId == other.remoteId &&
          variant == other.variant &&
          localPath == other.localPath &&
          sizeBytes == other.sizeBytes &&
          lastAccess == other.lastAccess;
}
