// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Spring Boot build-info block (generated by the `build-info` goal).
class BuildInfo {
  final String? artifact;
  final String? name;
  final String? time;
  final String? version;
  final String? group;

  const BuildInfo({
    this.artifact,
    this.name,
    this.time,
    this.version,
    this.group,
  });

  @override
  int get hashCode =>
      artifact.hashCode ^
      name.hashCode ^
      time.hashCode ^
      version.hashCode ^
      group.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuildInfo &&
          runtimeType == other.runtimeType &&
          artifact == other.artifact &&
          name == other.name &&
          time == other.time &&
          version == other.version &&
          group == other.group;
}

class GitCommit {
  final String? id;
  final String? time;

  const GitCommit({
    this.id,
    this.time,
  });

  @override
  int get hashCode => id.hashCode ^ time.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitCommit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          time == other.time;
}

/// Spring Boot git block (git.properties).
class GitInfo {
  final String? branch;
  final GitCommit? commit;

  const GitInfo({
    this.branch,
    this.commit,
  });

  @override
  int get hashCode => branch.hashCode ^ commit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitInfo &&
          runtimeType == other.runtimeType &&
          branch == other.branch &&
          commit == other.commit;
}

/// Minimal LibraryDto (`GET /api/v1/libraries`, plain array).
/// Unknown fields (scan flags, import flags, ...) are ignored by serde.
class Library {
  final String id;
  final String name;
  final String root;
  final bool? unavailable;

  const Library({
    required this.id,
    required this.name,
    required this.root,
    this.unavailable,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ root.hashCode ^ unavailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Library &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          root == other.root &&
          unavailable == other.unavailable;
}

/// `GET /actuator/info` — the snapshot-sanctioned "Get server information".
class ServerInfo {
  final BuildInfo? build;
  final GitInfo? git;

  const ServerInfo({
    this.build,
    this.git,
  });

  @override
  int get hashCode => build.hashCode ^ git.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerInfo &&
          runtimeType == other.runtimeType &&
          build == other.build &&
          git == other.git;
}
