// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// How authentication credentials are presented to Komga.
enum AuthType {
  apiKey,
  basic,
  ;
}

/// A saved Komga server profile.
///
/// Credentials are never stored here — only `credential_ref` referencing
/// platform credential storage (Keychain / Android Keystore).
class ServerProfile {
  final String id;
  final String displayName;
  final String baseUrl;
  final AuthType authType;

  /// Reference into Keychain / Android Keystore; never the secret itself.
  final String? credentialRef;

  /// Capabilities discovered during connection test, e.g. "sse".
  final List<String> capabilities;

  /// RFC 3339 timestamp of the last successful connection.
  final String? lastSuccessfulConnection;

  const ServerProfile({
    required this.id,
    required this.displayName,
    required this.baseUrl,
    required this.authType,
    this.credentialRef,
    required this.capabilities,
    this.lastSuccessfulConnection,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      baseUrl.hashCode ^
      authType.hashCode ^
      credentialRef.hashCode ^
      capabilities.hashCode ^
      lastSuccessfulConnection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerProfile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          baseUrl == other.baseUrl &&
          authType == other.authType &&
          credentialRef == other.credentialRef &&
          capabilities == other.capabilities &&
          lastSuccessfulConnection == other.lastSuccessfulConnection;
}
