// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'ffi/application.dart';
import 'ffi/bridge.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'model/server.dart';
import 'model/server_profile.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'store/series.dart';
import 'sync/bootstrap.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 169164183;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'komga_core',
    ioDirectory: '../komga_core/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<BootstrapSummary> crateFfiBridgeBootstrap(
      {required String dbPath,
      required String serverId,
      required String baseUrl,
      required String apiKey});

  Future<bool> crateFfiBridgeDeleteServer(
      {required String dbPath, required String serverId});

  Future<List<SeriesRow>> crateFfiBridgeFetchSeries(
      {required String dbPath,
      required String serverId,
      required PlatformInt64 limit,
      required PlatformInt64 offset});

  Future<String?> crateFfiBridgeGetActiveServer({required String dbPath});

  Future<ServerProfile?> crateFfiBridgeGetServer(
      {required String dbPath, required String serverId});

  Future<List<ServerProfile>> crateFfiBridgeListServers(
      {required String dbPath});

  Future<void> crateFfiBridgeSaveLibraries(
      {required String dbPath,
      required String serverId,
      required List<Library> libraries});

  Future<void> crateFfiBridgeSaveServer(
      {required String dbPath, required ServerProfile profile});

  Future<void> crateFfiBridgeSetActiveServer(
      {required String dbPath, required String serverId});

  Future<ConnectionResult> crateFfiBridgeTestConnection(
      {required String baseUrl, required String apiKey});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BootstrapSummary> crateFfiBridgeBootstrap(
      {required String dbPath,
      required String serverId,
      required String baseUrl,
      required String apiKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(baseUrl, serializer);
        sse_encode_String(apiKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bootstrap_summary,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateFfiBridgeBootstrapConstMeta,
      argValues: [dbPath, serverId, baseUrl, apiKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiBridgeBootstrapConstMeta => const TaskConstMeta(
        debugName: "bootstrap",
        argNames: ["dbPath", "serverId", "baseUrl", "apiKey"],
      );

  @override
  Future<bool> crateFfiBridgeDeleteServer(
      {required String dbPath, required String serverId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(serverId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateFfiBridgeDeleteServerConstMeta,
      argValues: [dbPath, serverId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiBridgeDeleteServerConstMeta => const TaskConstMeta(
        debugName: "delete_server",
        argNames: ["dbPath", "serverId"],
      );

  @override
  Future<List<SeriesRow>> crateFfiBridgeFetchSeries(
      {required String dbPath,
      required String serverId,
      required PlatformInt64 limit,
      required PlatformInt64 offset}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_i_64(limit, serializer);
        sse_encode_i_64(offset, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_series_row,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateFfiBridgeFetchSeriesConstMeta,
      argValues: [dbPath, serverId, limit, offset],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiBridgeFetchSeriesConstMeta => const TaskConstMeta(
        debugName: "fetch_series",
        argNames: ["dbPath", "serverId", "limit", "offset"],
      );

  @override
  Future<String?> crateFfiBridgeGetActiveServer({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateFfiBridgeGetActiveServerConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiBridgeGetActiveServerConstMeta =>
      const TaskConstMeta(
        debugName: "get_active_server",
        argNames: ["dbPath"],
      );

  @override
  Future<ServerProfile?> crateFfiBridgeGetServer(
      {required String dbPath, required String serverId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(serverId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_server_profile,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateFfiBridgeGetServerConstMeta,
      argValues: [dbPath, serverId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiBridgeGetServerConstMeta => const TaskConstMeta(
        debugName: "get_server",
        argNames: ["dbPath", "serverId"],
      );

  @override
  Future<List<ServerProfile>> crateFfiBridgeListServers(
      {required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_server_profile,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateFfiBridgeListServersConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiBridgeListServersConstMeta => const TaskConstMeta(
        debugName: "list_servers",
        argNames: ["dbPath"],
      );

  @override
  Future<void> crateFfiBridgeSaveLibraries(
      {required String dbPath,
      required String serverId,
      required List<Library> libraries}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_list_library(libraries, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateFfiBridgeSaveLibrariesConstMeta,
      argValues: [dbPath, serverId, libraries],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiBridgeSaveLibrariesConstMeta =>
      const TaskConstMeta(
        debugName: "save_libraries",
        argNames: ["dbPath", "serverId", "libraries"],
      );

  @override
  Future<void> crateFfiBridgeSaveServer(
      {required String dbPath, required ServerProfile profile}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_box_autoadd_server_profile(profile, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateFfiBridgeSaveServerConstMeta,
      argValues: [dbPath, profile],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiBridgeSaveServerConstMeta => const TaskConstMeta(
        debugName: "save_server",
        argNames: ["dbPath", "profile"],
      );

  @override
  Future<void> crateFfiBridgeSetActiveServer(
      {required String dbPath, required String serverId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(serverId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateFfiBridgeSetActiveServerConstMeta,
      argValues: [dbPath, serverId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiBridgeSetActiveServerConstMeta =>
      const TaskConstMeta(
        debugName: "set_active_server",
        argNames: ["dbPath", "serverId"],
      );

  @override
  Future<ConnectionResult> crateFfiBridgeTestConnection(
      {required String baseUrl, required String apiKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(baseUrl, serializer);
        sse_encode_String(apiKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_connection_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateFfiBridgeTestConnectionConstMeta,
      argValues: [baseUrl, apiKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiBridgeTestConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "test_connection",
        argNames: ["baseUrl", "apiKey"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AuthType dco_decode_auth_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AuthType.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BootstrapSummary dco_decode_bootstrap_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BootstrapSummary(
      serverId: dco_decode_String(arr[0]),
      syncedSeries: dco_decode_usize(arr[1]),
      totalElements: dco_decode_i_64(arr[2]),
      hasMorePages: dco_decode_bool(arr[3]),
    );
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BuildInfo dco_decode_box_autoadd_build_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_build_info(raw);
  }

  @protected
  GitCommit dco_decode_box_autoadd_git_commit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_git_commit(raw);
  }

  @protected
  GitInfo dco_decode_box_autoadd_git_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_git_info(raw);
  }

  @protected
  ServerProfile dco_decode_box_autoadd_server_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_server_profile(raw);
  }

  @protected
  BuildInfo dco_decode_build_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BuildInfo(
      artifact: dco_decode_opt_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      time: dco_decode_opt_String(arr[2]),
      version: dco_decode_opt_String(arr[3]),
      group: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  ConnectionResult dco_decode_connection_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ConnectionResult(
      serverInfo: dco_decode_server_info(arr[0]),
      serverVersion: dco_decode_opt_String(arr[1]),
      libraries: dco_decode_list_library(arr[2]),
      capabilities: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  GitCommit dco_decode_git_commit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GitCommit(
      id: dco_decode_opt_String(arr[0]),
      time: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  GitInfo dco_decode_git_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GitInfo(
      branch: dco_decode_opt_String(arr[0]),
      commit: dco_decode_opt_box_autoadd_git_commit(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Library dco_decode_library(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Library(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      root: dco_decode_String(arr[2]),
      unavailable: dco_decode_opt_box_autoadd_bool(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Library> dco_decode_list_library(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_library).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SeriesRow> dco_decode_list_series_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_series_row).toList();
  }

  @protected
  List<ServerProfile> dco_decode_list_server_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_server_profile).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  BuildInfo? dco_decode_opt_box_autoadd_build_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_build_info(raw);
  }

  @protected
  GitCommit? dco_decode_opt_box_autoadd_git_commit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_git_commit(raw);
  }

  @protected
  GitInfo? dco_decode_opt_box_autoadd_git_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_git_info(raw);
  }

  @protected
  ServerProfile? dco_decode_opt_box_autoadd_server_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_server_profile(raw);
  }

  @protected
  SeriesRow dco_decode_series_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return SeriesRow(
      serverId: dco_decode_String(arr[0]),
      remoteId: dco_decode_String(arr[1]),
      libraryId: dco_decode_String(arr[2]),
      name: dco_decode_String(arr[3]),
      sortName: dco_decode_opt_String(arr[4]),
      status: dco_decode_opt_String(arr[5]),
      createdAt: dco_decode_opt_String(arr[6]),
      lastModified: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  ServerInfo dco_decode_server_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ServerInfo(
      build: dco_decode_opt_box_autoadd_build_info(arr[0]),
      git: dco_decode_opt_box_autoadd_git_info(arr[1]),
    );
  }

  @protected
  ServerProfile dco_decode_server_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ServerProfile(
      id: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      baseUrl: dco_decode_String(arr[2]),
      authType: dco_decode_auth_type(arr[3]),
      credentialRef: dco_decode_opt_String(arr[4]),
      capabilities: dco_decode_list_String(arr[5]),
      lastSuccessfulConnection: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AuthType sse_decode_auth_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AuthType.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BootstrapSummary sse_decode_bootstrap_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_serverId = sse_decode_String(deserializer);
    var var_syncedSeries = sse_decode_usize(deserializer);
    var var_totalElements = sse_decode_i_64(deserializer);
    var var_hasMorePages = sse_decode_bool(deserializer);
    return BootstrapSummary(
        serverId: var_serverId,
        syncedSeries: var_syncedSeries,
        totalElements: var_totalElements,
        hasMorePages: var_hasMorePages);
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  BuildInfo sse_decode_box_autoadd_build_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_build_info(deserializer));
  }

  @protected
  GitCommit sse_decode_box_autoadd_git_commit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_git_commit(deserializer));
  }

  @protected
  GitInfo sse_decode_box_autoadd_git_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_git_info(deserializer));
  }

  @protected
  ServerProfile sse_decode_box_autoadd_server_profile(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_server_profile(deserializer));
  }

  @protected
  BuildInfo sse_decode_build_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_artifact = sse_decode_opt_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_time = sse_decode_opt_String(deserializer);
    var var_version = sse_decode_opt_String(deserializer);
    var var_group = sse_decode_opt_String(deserializer);
    return BuildInfo(
        artifact: var_artifact,
        name: var_name,
        time: var_time,
        version: var_version,
        group: var_group);
  }

  @protected
  ConnectionResult sse_decode_connection_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_serverInfo = sse_decode_server_info(deserializer);
    var var_serverVersion = sse_decode_opt_String(deserializer);
    var var_libraries = sse_decode_list_library(deserializer);
    var var_capabilities = sse_decode_list_String(deserializer);
    return ConnectionResult(
        serverInfo: var_serverInfo,
        serverVersion: var_serverVersion,
        libraries: var_libraries,
        capabilities: var_capabilities);
  }

  @protected
  GitCommit sse_decode_git_commit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_String(deserializer);
    var var_time = sse_decode_opt_String(deserializer);
    return GitCommit(id: var_id, time: var_time);
  }

  @protected
  GitInfo sse_decode_git_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_branch = sse_decode_opt_String(deserializer);
    var var_commit = sse_decode_opt_box_autoadd_git_commit(deserializer);
    return GitInfo(branch: var_branch, commit: var_commit);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Library sse_decode_library(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_root = sse_decode_String(deserializer);
    var var_unavailable = sse_decode_opt_box_autoadd_bool(deserializer);
    return Library(
        id: var_id,
        name: var_name,
        root: var_root,
        unavailable: var_unavailable);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Library> sse_decode_list_library(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Library>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_library(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SeriesRow> sse_decode_list_series_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SeriesRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_series_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<ServerProfile> sse_decode_list_server_profile(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ServerProfile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_server_profile(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BuildInfo? sse_decode_opt_box_autoadd_build_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_build_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  GitCommit? sse_decode_opt_box_autoadd_git_commit(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_git_commit(deserializer));
    } else {
      return null;
    }
  }

  @protected
  GitInfo? sse_decode_opt_box_autoadd_git_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_git_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ServerProfile? sse_decode_opt_box_autoadd_server_profile(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_server_profile(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SeriesRow sse_decode_series_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_serverId = sse_decode_String(deserializer);
    var var_remoteId = sse_decode_String(deserializer);
    var var_libraryId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_sortName = sse_decode_opt_String(deserializer);
    var var_status = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_opt_String(deserializer);
    var var_lastModified = sse_decode_opt_String(deserializer);
    return SeriesRow(
        serverId: var_serverId,
        remoteId: var_remoteId,
        libraryId: var_libraryId,
        name: var_name,
        sortName: var_sortName,
        status: var_status,
        createdAt: var_createdAt,
        lastModified: var_lastModified);
  }

  @protected
  ServerInfo sse_decode_server_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_build = sse_decode_opt_box_autoadd_build_info(deserializer);
    var var_git = sse_decode_opt_box_autoadd_git_info(deserializer);
    return ServerInfo(build: var_build, git: var_git);
  }

  @protected
  ServerProfile sse_decode_server_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_baseUrl = sse_decode_String(deserializer);
    var var_authType = sse_decode_auth_type(deserializer);
    var var_credentialRef = sse_decode_opt_String(deserializer);
    var var_capabilities = sse_decode_list_String(deserializer);
    var var_lastSuccessfulConnection = sse_decode_opt_String(deserializer);
    return ServerProfile(
        id: var_id,
        displayName: var_displayName,
        baseUrl: var_baseUrl,
        authType: var_authType,
        credentialRef: var_credentialRef,
        capabilities: var_capabilities,
        lastSuccessfulConnection: var_lastSuccessfulConnection);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_auth_type(AuthType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bootstrap_summary(
      BootstrapSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.serverId, serializer);
    sse_encode_usize(self.syncedSeries, serializer);
    sse_encode_i_64(self.totalElements, serializer);
    sse_encode_bool(self.hasMorePages, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_build_info(
      BuildInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_build_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_git_commit(
      GitCommit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_git_commit(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_git_info(GitInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_git_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_server_profile(
      ServerProfile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_server_profile(self, serializer);
  }

  @protected
  void sse_encode_build_info(BuildInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.artifact, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_String(self.time, serializer);
    sse_encode_opt_String(self.version, serializer);
    sse_encode_opt_String(self.group, serializer);
  }

  @protected
  void sse_encode_connection_result(
      ConnectionResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_server_info(self.serverInfo, serializer);
    sse_encode_opt_String(self.serverVersion, serializer);
    sse_encode_list_library(self.libraries, serializer);
    sse_encode_list_String(self.capabilities, serializer);
  }

  @protected
  void sse_encode_git_commit(GitCommit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.id, serializer);
    sse_encode_opt_String(self.time, serializer);
  }

  @protected
  void sse_encode_git_info(GitInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.branch, serializer);
    sse_encode_opt_box_autoadd_git_commit(self.commit, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_library(Library self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.root, serializer);
    sse_encode_opt_box_autoadd_bool(self.unavailable, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_library(List<Library> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_library(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_series_row(
      List<SeriesRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_series_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_server_profile(
      List<ServerProfile> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_server_profile(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_build_info(
      BuildInfo? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_build_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_git_commit(
      GitCommit? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_git_commit(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_git_info(
      GitInfo? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_git_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_server_profile(
      ServerProfile? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_server_profile(self, serializer);
    }
  }

  @protected
  void sse_encode_series_row(SeriesRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.serverId, serializer);
    sse_encode_String(self.remoteId, serializer);
    sse_encode_String(self.libraryId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.sortName, serializer);
    sse_encode_opt_String(self.status, serializer);
    sse_encode_opt_String(self.createdAt, serializer);
    sse_encode_opt_String(self.lastModified, serializer);
  }

  @protected
  void sse_encode_server_info(ServerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_build_info(self.build, serializer);
    sse_encode_opt_box_autoadd_git_info(self.git, serializer);
  }

  @protected
  void sse_encode_server_profile(ServerProfile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.baseUrl, serializer);
    sse_encode_auth_type(self.authType, serializer);
    sse_encode_opt_String(self.credentialRef, serializer);
    sse_encode_list_String(self.capabilities, serializer);
    sse_encode_opt_String(self.lastSuccessfulConnection, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
