// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'ffi/application.dart';
import 'ffi/bridge.dart';
import 'frb_generated.dart';
import 'model/server.dart';
import 'model/server_profile.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'store.dart';
import 'store/books.dart';
import 'store/collections.dart';
import 'store/prune.dart';
import 'store/query.dart';
import 'store/read_progress.dart';
import 'store/readlists.dart';
import 'store/series.dart';
import 'store/sync_state.dart';
import 'store/thumbnails.dart';
import 'sync/bootstrap.dart';
import 'sync/full.dart';
import 'sync/reconcile.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthType dco_decode_auth_type(dynamic raw);

  @protected
  AuthorRow dco_decode_author_row(dynamic raw);

  @protected
  BookDetailRow dco_decode_book_detail_row(dynamic raw);

  @protected
  BookPageResult dco_decode_book_page_result(dynamic raw);

  @protected
  BookRow dco_decode_book_row(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BootstrapSummary dco_decode_bootstrap_summary(dynamic raw);

  @protected
  BookDetailRow dco_decode_box_autoadd_book_detail_row(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  BuildInfo dco_decode_box_autoadd_build_info(dynamic raw);

  @protected
  CollectionDetailRow dco_decode_box_autoadd_collection_detail_row(dynamic raw);

  @protected
  DeviceProfileDto dco_decode_box_autoadd_device_profile_dto(dynamic raw);

  @protected
  DownloadPumpDto dco_decode_box_autoadd_download_pump_dto(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  GitCommit dco_decode_box_autoadd_git_commit(dynamic raw);

  @protected
  GitInfo dco_decode_box_autoadd_git_info(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LibraryCountRow dco_decode_box_autoadd_library_count_row(dynamic raw);

  @protected
  ReaderSettingsDto dco_decode_box_autoadd_reader_settings_dto(dynamic raw);

  @protected
  ReadlistDetailRow dco_decode_box_autoadd_readlist_detail_row(dynamic raw);

  @protected
  SeriesDetailRow dco_decode_box_autoadd_series_detail_row(dynamic raw);

  @protected
  ServerProfile dco_decode_box_autoadd_server_profile(dynamic raw);

  @protected
  SsePollResult dco_decode_box_autoadd_sse_poll_result(dynamic raw);

  @protected
  BuildInfo dco_decode_build_info(dynamic raw);

  @protected
  CacheCleanupDto dco_decode_cache_cleanup_dto(dynamic raw);

  @protected
  CacheStatsDto dco_decode_cache_stats_dto(dynamic raw);

  @protected
  CollectionDetailRow dco_decode_collection_detail_row(dynamic raw);

  @protected
  CollectionPageResult dco_decode_collection_page_result(dynamic raw);

  @protected
  CollectionRef dco_decode_collection_ref(dynamic raw);

  @protected
  CollectionRow dco_decode_collection_row(dynamic raw);

  @protected
  ConnectionResult dco_decode_connection_result(dynamic raw);

  @protected
  ContinueReadingRow dco_decode_continue_reading_row(dynamic raw);

  @protected
  DeviceProfileDto dco_decode_device_profile_dto(dynamic raw);

  @protected
  DownloadBookDto dco_decode_download_book_dto(dynamic raw);

  @protected
  DownloadDeleteDto dco_decode_download_delete_dto(dynamic raw);

  @protected
  DownloadPumpDto dco_decode_download_pump_dto(dynamic raw);

  @protected
  DownloadSweepDto dco_decode_download_sweep_dto(dynamic raw);

  @protected
  EntitySyncState dco_decode_entity_sync_state(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FilterOptions dco_decode_filter_options(dynamic raw);

  @protected
  FullSyncSummary dco_decode_full_sync_summary(dynamic raw);

  @protected
  GitCommit dco_decode_git_commit(dynamic raw);

  @protected
  GitInfo dco_decode_git_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Library dco_decode_library(dynamic raw);

  @protected
  LibraryCountRow dco_decode_library_count_row(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AuthorRow> dco_decode_list_author_row(dynamic raw);

  @protected
  List<BookRow> dco_decode_list_book_row(dynamic raw);

  @protected
  List<CollectionRef> dco_decode_list_collection_ref(dynamic raw);

  @protected
  List<CollectionRow> dco_decode_list_collection_row(dynamic raw);

  @protected
  List<ContinueReadingRow> dco_decode_list_continue_reading_row(dynamic raw);

  @protected
  List<DownloadBookDto> dco_decode_list_download_book_dto(dynamic raw);

  @protected
  List<EntitySyncState> dco_decode_list_entity_sync_state(dynamic raw);

  @protected
  List<Library> dco_decode_list_library(dynamic raw);

  @protected
  List<LibraryCountRow> dco_decode_list_library_count_row(dynamic raw);

  @protected
  List<Uint32List> dco_decode_list_list_prim_u_32_strict(dynamic raw);

  @protected
  List<OutboxEntryDto> dco_decode_list_outbox_entry_dto(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReadlistRow> dco_decode_list_readlist_row(dynamic raw);

  @protected
  List<SeriesRow> dco_decode_list_series_row(dynamic raw);

  @protected
  List<ServerProfile> dco_decode_list_server_profile(dynamic raw);

  @protected
  List<StorageBookDto> dco_decode_list_storage_book_dto(dynamic raw);

  @protected
  List<ThumbnailRow> dco_decode_list_thumbnail_row(dynamic raw);

  @protected
  List<Tombstone> dco_decode_list_tombstone(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BookDetailRow? dco_decode_opt_box_autoadd_book_detail_row(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  BuildInfo? dco_decode_opt_box_autoadd_build_info(dynamic raw);

  @protected
  CollectionDetailRow? dco_decode_opt_box_autoadd_collection_detail_row(
      dynamic raw);

  @protected
  DownloadPumpDto? dco_decode_opt_box_autoadd_download_pump_dto(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  GitCommit? dco_decode_opt_box_autoadd_git_commit(dynamic raw);

  @protected
  GitInfo? dco_decode_opt_box_autoadd_git_info(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  LibraryCountRow? dco_decode_opt_box_autoadd_library_count_row(dynamic raw);

  @protected
  ReadlistDetailRow? dco_decode_opt_box_autoadd_readlist_detail_row(
      dynamic raw);

  @protected
  SeriesDetailRow? dco_decode_opt_box_autoadd_series_detail_row(dynamic raw);

  @protected
  ServerProfile? dco_decode_opt_box_autoadd_server_profile(dynamic raw);

  @protected
  SsePollResult? dco_decode_opt_box_autoadd_sse_poll_result(dynamic raw);

  @protected
  OutboxEntryDto dco_decode_outbox_entry_dto(dynamic raw);

  @protected
  OutboxStatusDto dco_decode_outbox_status_dto(dynamic raw);

  @protected
  ReaderBookDto dco_decode_reader_book_dto(dynamic raw);

  @protected
  ReaderLayoutDto dco_decode_reader_layout_dto(dynamic raw);

  @protected
  ReaderSettingsDto dco_decode_reader_settings_dto(dynamic raw);

  @protected
  ReaderTurnDto dco_decode_reader_turn_dto(dynamic raw);

  @protected
  ReaderWindowDto dco_decode_reader_window_dto(dynamic raw);

  @protected
  ReadlistDetailRow dco_decode_readlist_detail_row(dynamic raw);

  @protected
  ReadlistPageResult dco_decode_readlist_page_result(dynamic raw);

  @protected
  ReadlistRow dco_decode_readlist_row(dynamic raw);

  @protected
  ReconcileSummary dco_decode_reconcile_summary(dynamic raw);

  @protected
  SeriesDetailRow dco_decode_series_detail_row(dynamic raw);

  @protected
  SeriesPageResult dco_decode_series_page_result(dynamic raw);

  @protected
  SeriesRow dco_decode_series_row(dynamic raw);

  @protected
  ServerInfo dco_decode_server_info(dynamic raw);

  @protected
  ServerProfile dco_decode_server_profile(dynamic raw);

  @protected
  SsePollResult dco_decode_sse_poll_result(dynamic raw);

  @protected
  StorageBookDto dco_decode_storage_book_dto(dynamic raw);

  @protected
  StorageDto dco_decode_storage_dto(dynamic raw);

  @protected
  ThumbnailRow dco_decode_thumbnail_row(dynamic raw);

  @protected
  Tombstone dco_decode_tombstone(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UploadOutcomeDto dco_decode_upload_outcome_dto(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthType sse_decode_auth_type(SseDeserializer deserializer);

  @protected
  AuthorRow sse_decode_author_row(SseDeserializer deserializer);

  @protected
  BookDetailRow sse_decode_book_detail_row(SseDeserializer deserializer);

  @protected
  BookPageResult sse_decode_book_page_result(SseDeserializer deserializer);

  @protected
  BookRow sse_decode_book_row(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BootstrapSummary sse_decode_bootstrap_summary(SseDeserializer deserializer);

  @protected
  BookDetailRow sse_decode_box_autoadd_book_detail_row(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  BuildInfo sse_decode_box_autoadd_build_info(SseDeserializer deserializer);

  @protected
  CollectionDetailRow sse_decode_box_autoadd_collection_detail_row(
      SseDeserializer deserializer);

  @protected
  DeviceProfileDto sse_decode_box_autoadd_device_profile_dto(
      SseDeserializer deserializer);

  @protected
  DownloadPumpDto sse_decode_box_autoadd_download_pump_dto(
      SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GitCommit sse_decode_box_autoadd_git_commit(SseDeserializer deserializer);

  @protected
  GitInfo sse_decode_box_autoadd_git_info(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LibraryCountRow sse_decode_box_autoadd_library_count_row(
      SseDeserializer deserializer);

  @protected
  ReaderSettingsDto sse_decode_box_autoadd_reader_settings_dto(
      SseDeserializer deserializer);

  @protected
  ReadlistDetailRow sse_decode_box_autoadd_readlist_detail_row(
      SseDeserializer deserializer);

  @protected
  SeriesDetailRow sse_decode_box_autoadd_series_detail_row(
      SseDeserializer deserializer);

  @protected
  ServerProfile sse_decode_box_autoadd_server_profile(
      SseDeserializer deserializer);

  @protected
  SsePollResult sse_decode_box_autoadd_sse_poll_result(
      SseDeserializer deserializer);

  @protected
  BuildInfo sse_decode_build_info(SseDeserializer deserializer);

  @protected
  CacheCleanupDto sse_decode_cache_cleanup_dto(SseDeserializer deserializer);

  @protected
  CacheStatsDto sse_decode_cache_stats_dto(SseDeserializer deserializer);

  @protected
  CollectionDetailRow sse_decode_collection_detail_row(
      SseDeserializer deserializer);

  @protected
  CollectionPageResult sse_decode_collection_page_result(
      SseDeserializer deserializer);

  @protected
  CollectionRef sse_decode_collection_ref(SseDeserializer deserializer);

  @protected
  CollectionRow sse_decode_collection_row(SseDeserializer deserializer);

  @protected
  ConnectionResult sse_decode_connection_result(SseDeserializer deserializer);

  @protected
  ContinueReadingRow sse_decode_continue_reading_row(
      SseDeserializer deserializer);

  @protected
  DeviceProfileDto sse_decode_device_profile_dto(SseDeserializer deserializer);

  @protected
  DownloadBookDto sse_decode_download_book_dto(SseDeserializer deserializer);

  @protected
  DownloadDeleteDto sse_decode_download_delete_dto(
      SseDeserializer deserializer);

  @protected
  DownloadPumpDto sse_decode_download_pump_dto(SseDeserializer deserializer);

  @protected
  DownloadSweepDto sse_decode_download_sweep_dto(SseDeserializer deserializer);

  @protected
  EntitySyncState sse_decode_entity_sync_state(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FilterOptions sse_decode_filter_options(SseDeserializer deserializer);

  @protected
  FullSyncSummary sse_decode_full_sync_summary(SseDeserializer deserializer);

  @protected
  GitCommit sse_decode_git_commit(SseDeserializer deserializer);

  @protected
  GitInfo sse_decode_git_info(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Library sse_decode_library(SseDeserializer deserializer);

  @protected
  LibraryCountRow sse_decode_library_count_row(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AuthorRow> sse_decode_list_author_row(SseDeserializer deserializer);

  @protected
  List<BookRow> sse_decode_list_book_row(SseDeserializer deserializer);

  @protected
  List<CollectionRef> sse_decode_list_collection_ref(
      SseDeserializer deserializer);

  @protected
  List<CollectionRow> sse_decode_list_collection_row(
      SseDeserializer deserializer);

  @protected
  List<ContinueReadingRow> sse_decode_list_continue_reading_row(
      SseDeserializer deserializer);

  @protected
  List<DownloadBookDto> sse_decode_list_download_book_dto(
      SseDeserializer deserializer);

  @protected
  List<EntitySyncState> sse_decode_list_entity_sync_state(
      SseDeserializer deserializer);

  @protected
  List<Library> sse_decode_list_library(SseDeserializer deserializer);

  @protected
  List<LibraryCountRow> sse_decode_list_library_count_row(
      SseDeserializer deserializer);

  @protected
  List<Uint32List> sse_decode_list_list_prim_u_32_strict(
      SseDeserializer deserializer);

  @protected
  List<OutboxEntryDto> sse_decode_list_outbox_entry_dto(
      SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReadlistRow> sse_decode_list_readlist_row(SseDeserializer deserializer);

  @protected
  List<SeriesRow> sse_decode_list_series_row(SseDeserializer deserializer);

  @protected
  List<ServerProfile> sse_decode_list_server_profile(
      SseDeserializer deserializer);

  @protected
  List<StorageBookDto> sse_decode_list_storage_book_dto(
      SseDeserializer deserializer);

  @protected
  List<ThumbnailRow> sse_decode_list_thumbnail_row(
      SseDeserializer deserializer);

  @protected
  List<Tombstone> sse_decode_list_tombstone(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BookDetailRow? sse_decode_opt_box_autoadd_book_detail_row(
      SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  BuildInfo? sse_decode_opt_box_autoadd_build_info(
      SseDeserializer deserializer);

  @protected
  CollectionDetailRow? sse_decode_opt_box_autoadd_collection_detail_row(
      SseDeserializer deserializer);

  @protected
  DownloadPumpDto? sse_decode_opt_box_autoadd_download_pump_dto(
      SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GitCommit? sse_decode_opt_box_autoadd_git_commit(
      SseDeserializer deserializer);

  @protected
  GitInfo? sse_decode_opt_box_autoadd_git_info(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LibraryCountRow? sse_decode_opt_box_autoadd_library_count_row(
      SseDeserializer deserializer);

  @protected
  ReadlistDetailRow? sse_decode_opt_box_autoadd_readlist_detail_row(
      SseDeserializer deserializer);

  @protected
  SeriesDetailRow? sse_decode_opt_box_autoadd_series_detail_row(
      SseDeserializer deserializer);

  @protected
  ServerProfile? sse_decode_opt_box_autoadd_server_profile(
      SseDeserializer deserializer);

  @protected
  SsePollResult? sse_decode_opt_box_autoadd_sse_poll_result(
      SseDeserializer deserializer);

  @protected
  OutboxEntryDto sse_decode_outbox_entry_dto(SseDeserializer deserializer);

  @protected
  OutboxStatusDto sse_decode_outbox_status_dto(SseDeserializer deserializer);

  @protected
  ReaderBookDto sse_decode_reader_book_dto(SseDeserializer deserializer);

  @protected
  ReaderLayoutDto sse_decode_reader_layout_dto(SseDeserializer deserializer);

  @protected
  ReaderSettingsDto sse_decode_reader_settings_dto(
      SseDeserializer deserializer);

  @protected
  ReaderTurnDto sse_decode_reader_turn_dto(SseDeserializer deserializer);

  @protected
  ReaderWindowDto sse_decode_reader_window_dto(SseDeserializer deserializer);

  @protected
  ReadlistDetailRow sse_decode_readlist_detail_row(
      SseDeserializer deserializer);

  @protected
  ReadlistPageResult sse_decode_readlist_page_result(
      SseDeserializer deserializer);

  @protected
  ReadlistRow sse_decode_readlist_row(SseDeserializer deserializer);

  @protected
  ReconcileSummary sse_decode_reconcile_summary(SseDeserializer deserializer);

  @protected
  SeriesDetailRow sse_decode_series_detail_row(SseDeserializer deserializer);

  @protected
  SeriesPageResult sse_decode_series_page_result(SseDeserializer deserializer);

  @protected
  SeriesRow sse_decode_series_row(SseDeserializer deserializer);

  @protected
  ServerInfo sse_decode_server_info(SseDeserializer deserializer);

  @protected
  ServerProfile sse_decode_server_profile(SseDeserializer deserializer);

  @protected
  SsePollResult sse_decode_sse_poll_result(SseDeserializer deserializer);

  @protected
  StorageBookDto sse_decode_storage_book_dto(SseDeserializer deserializer);

  @protected
  StorageDto sse_decode_storage_dto(SseDeserializer deserializer);

  @protected
  ThumbnailRow sse_decode_thumbnail_row(SseDeserializer deserializer);

  @protected
  Tombstone sse_decode_tombstone(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UploadOutcomeDto sse_decode_upload_outcome_dto(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_auth_type(AuthType self, SseSerializer serializer);

  @protected
  void sse_encode_author_row(AuthorRow self, SseSerializer serializer);

  @protected
  void sse_encode_book_detail_row(BookDetailRow self, SseSerializer serializer);

  @protected
  void sse_encode_book_page_result(
      BookPageResult self, SseSerializer serializer);

  @protected
  void sse_encode_book_row(BookRow self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bootstrap_summary(
      BootstrapSummary self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_book_detail_row(
      BookDetailRow self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_build_info(
      BuildInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_collection_detail_row(
      CollectionDetailRow self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_device_profile_dto(
      DeviceProfileDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_download_pump_dto(
      DownloadPumpDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_git_commit(
      GitCommit self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_git_info(GitInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_library_count_row(
      LibraryCountRow self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_reader_settings_dto(
      ReaderSettingsDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_readlist_detail_row(
      ReadlistDetailRow self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_series_detail_row(
      SeriesDetailRow self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_server_profile(
      ServerProfile self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sse_poll_result(
      SsePollResult self, SseSerializer serializer);

  @protected
  void sse_encode_build_info(BuildInfo self, SseSerializer serializer);

  @protected
  void sse_encode_cache_cleanup_dto(
      CacheCleanupDto self, SseSerializer serializer);

  @protected
  void sse_encode_cache_stats_dto(CacheStatsDto self, SseSerializer serializer);

  @protected
  void sse_encode_collection_detail_row(
      CollectionDetailRow self, SseSerializer serializer);

  @protected
  void sse_encode_collection_page_result(
      CollectionPageResult self, SseSerializer serializer);

  @protected
  void sse_encode_collection_ref(CollectionRef self, SseSerializer serializer);

  @protected
  void sse_encode_collection_row(CollectionRow self, SseSerializer serializer);

  @protected
  void sse_encode_connection_result(
      ConnectionResult self, SseSerializer serializer);

  @protected
  void sse_encode_continue_reading_row(
      ContinueReadingRow self, SseSerializer serializer);

  @protected
  void sse_encode_device_profile_dto(
      DeviceProfileDto self, SseSerializer serializer);

  @protected
  void sse_encode_download_book_dto(
      DownloadBookDto self, SseSerializer serializer);

  @protected
  void sse_encode_download_delete_dto(
      DownloadDeleteDto self, SseSerializer serializer);

  @protected
  void sse_encode_download_pump_dto(
      DownloadPumpDto self, SseSerializer serializer);

  @protected
  void sse_encode_download_sweep_dto(
      DownloadSweepDto self, SseSerializer serializer);

  @protected
  void sse_encode_entity_sync_state(
      EntitySyncState self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_filter_options(FilterOptions self, SseSerializer serializer);

  @protected
  void sse_encode_full_sync_summary(
      FullSyncSummary self, SseSerializer serializer);

  @protected
  void sse_encode_git_commit(GitCommit self, SseSerializer serializer);

  @protected
  void sse_encode_git_info(GitInfo self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_library(Library self, SseSerializer serializer);

  @protected
  void sse_encode_library_count_row(
      LibraryCountRow self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_author_row(
      List<AuthorRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_book_row(List<BookRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_collection_ref(
      List<CollectionRef> self, SseSerializer serializer);

  @protected
  void sse_encode_list_collection_row(
      List<CollectionRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_continue_reading_row(
      List<ContinueReadingRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_download_book_dto(
      List<DownloadBookDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_entity_sync_state(
      List<EntitySyncState> self, SseSerializer serializer);

  @protected
  void sse_encode_list_library(List<Library> self, SseSerializer serializer);

  @protected
  void sse_encode_list_library_count_row(
      List<LibraryCountRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_32_strict(
      List<Uint32List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_outbox_entry_dto(
      List<OutboxEntryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_readlist_row(
      List<ReadlistRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_series_row(
      List<SeriesRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_server_profile(
      List<ServerProfile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_storage_book_dto(
      List<StorageBookDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_thumbnail_row(
      List<ThumbnailRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tombstone(
      List<Tombstone> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_book_detail_row(
      BookDetailRow? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_build_info(
      BuildInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_collection_detail_row(
      CollectionDetailRow? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_download_pump_dto(
      DownloadPumpDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_git_commit(
      GitCommit? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_git_info(
      GitInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_library_count_row(
      LibraryCountRow? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_readlist_detail_row(
      ReadlistDetailRow? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_series_detail_row(
      SeriesDetailRow? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_server_profile(
      ServerProfile? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_sse_poll_result(
      SsePollResult? self, SseSerializer serializer);

  @protected
  void sse_encode_outbox_entry_dto(
      OutboxEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_outbox_status_dto(
      OutboxStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_reader_book_dto(ReaderBookDto self, SseSerializer serializer);

  @protected
  void sse_encode_reader_layout_dto(
      ReaderLayoutDto self, SseSerializer serializer);

  @protected
  void sse_encode_reader_settings_dto(
      ReaderSettingsDto self, SseSerializer serializer);

  @protected
  void sse_encode_reader_turn_dto(ReaderTurnDto self, SseSerializer serializer);

  @protected
  void sse_encode_reader_window_dto(
      ReaderWindowDto self, SseSerializer serializer);

  @protected
  void sse_encode_readlist_detail_row(
      ReadlistDetailRow self, SseSerializer serializer);

  @protected
  void sse_encode_readlist_page_result(
      ReadlistPageResult self, SseSerializer serializer);

  @protected
  void sse_encode_readlist_row(ReadlistRow self, SseSerializer serializer);

  @protected
  void sse_encode_reconcile_summary(
      ReconcileSummary self, SseSerializer serializer);

  @protected
  void sse_encode_series_detail_row(
      SeriesDetailRow self, SseSerializer serializer);

  @protected
  void sse_encode_series_page_result(
      SeriesPageResult self, SseSerializer serializer);

  @protected
  void sse_encode_series_row(SeriesRow self, SseSerializer serializer);

  @protected
  void sse_encode_server_info(ServerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_server_profile(ServerProfile self, SseSerializer serializer);

  @protected
  void sse_encode_sse_poll_result(SsePollResult self, SseSerializer serializer);

  @protected
  void sse_encode_storage_book_dto(
      StorageBookDto self, SseSerializer serializer);

  @protected
  void sse_encode_storage_dto(StorageDto self, SseSerializer serializer);

  @protected
  void sse_encode_thumbnail_row(ThumbnailRow self, SseSerializer serializer);

  @protected
  void sse_encode_tombstone(Tombstone self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_upload_outcome_dto(
      UploadOutcomeDto self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
