// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';
import 'ffi/application.dart';
import 'ffi/bridge.dart';
import 'frb_generated.dart';
import 'model/server.dart';
import 'model/server_profile.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'store/series.dart';
import 'store/thumbnails.dart';
import 'sync/bootstrap.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthType dco_decode_auth_type(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BootstrapSummary dco_decode_bootstrap_summary(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  BuildInfo dco_decode_box_autoadd_build_info(dynamic raw);

  @protected
  GitCommit dco_decode_box_autoadd_git_commit(dynamic raw);

  @protected
  GitInfo dco_decode_box_autoadd_git_info(dynamic raw);

  @protected
  ServerProfile dco_decode_box_autoadd_server_profile(dynamic raw);

  @protected
  BuildInfo dco_decode_build_info(dynamic raw);

  @protected
  ConnectionResult dco_decode_connection_result(dynamic raw);

  @protected
  GitCommit dco_decode_git_commit(dynamic raw);

  @protected
  GitInfo dco_decode_git_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Library dco_decode_library(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Library> dco_decode_list_library(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SeriesRow> dco_decode_list_series_row(dynamic raw);

  @protected
  List<ServerProfile> dco_decode_list_server_profile(dynamic raw);

  @protected
  List<ThumbnailRow> dco_decode_list_thumbnail_row(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  BuildInfo? dco_decode_opt_box_autoadd_build_info(dynamic raw);

  @protected
  GitCommit? dco_decode_opt_box_autoadd_git_commit(dynamic raw);

  @protected
  GitInfo? dco_decode_opt_box_autoadd_git_info(dynamic raw);

  @protected
  ServerProfile? dco_decode_opt_box_autoadd_server_profile(dynamic raw);

  @protected
  SeriesRow dco_decode_series_row(dynamic raw);

  @protected
  ServerInfo dco_decode_server_info(dynamic raw);

  @protected
  ServerProfile dco_decode_server_profile(dynamic raw);

  @protected
  ThumbnailRow dco_decode_thumbnail_row(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthType sse_decode_auth_type(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BootstrapSummary sse_decode_bootstrap_summary(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  BuildInfo sse_decode_box_autoadd_build_info(SseDeserializer deserializer);

  @protected
  GitCommit sse_decode_box_autoadd_git_commit(SseDeserializer deserializer);

  @protected
  GitInfo sse_decode_box_autoadd_git_info(SseDeserializer deserializer);

  @protected
  ServerProfile sse_decode_box_autoadd_server_profile(
      SseDeserializer deserializer);

  @protected
  BuildInfo sse_decode_build_info(SseDeserializer deserializer);

  @protected
  ConnectionResult sse_decode_connection_result(SseDeserializer deserializer);

  @protected
  GitCommit sse_decode_git_commit(SseDeserializer deserializer);

  @protected
  GitInfo sse_decode_git_info(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Library sse_decode_library(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Library> sse_decode_list_library(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SeriesRow> sse_decode_list_series_row(SseDeserializer deserializer);

  @protected
  List<ServerProfile> sse_decode_list_server_profile(
      SseDeserializer deserializer);

  @protected
  List<ThumbnailRow> sse_decode_list_thumbnail_row(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  BuildInfo? sse_decode_opt_box_autoadd_build_info(
      SseDeserializer deserializer);

  @protected
  GitCommit? sse_decode_opt_box_autoadd_git_commit(
      SseDeserializer deserializer);

  @protected
  GitInfo? sse_decode_opt_box_autoadd_git_info(SseDeserializer deserializer);

  @protected
  ServerProfile? sse_decode_opt_box_autoadd_server_profile(
      SseDeserializer deserializer);

  @protected
  SeriesRow sse_decode_series_row(SseDeserializer deserializer);

  @protected
  ServerInfo sse_decode_server_info(SseDeserializer deserializer);

  @protected
  ServerProfile sse_decode_server_profile(SseDeserializer deserializer);

  @protected
  ThumbnailRow sse_decode_thumbnail_row(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_auth_type(AuthType self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bootstrap_summary(
      BootstrapSummary self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_build_info(
      BuildInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_git_commit(
      GitCommit self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_git_info(GitInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_server_profile(
      ServerProfile self, SseSerializer serializer);

  @protected
  void sse_encode_build_info(BuildInfo self, SseSerializer serializer);

  @protected
  void sse_encode_connection_result(
      ConnectionResult self, SseSerializer serializer);

  @protected
  void sse_encode_git_commit(GitCommit self, SseSerializer serializer);

  @protected
  void sse_encode_git_info(GitInfo self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_library(Library self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_library(List<Library> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_series_row(
      List<SeriesRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_server_profile(
      List<ServerProfile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_thumbnail_row(
      List<ThumbnailRow> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_build_info(
      BuildInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_git_commit(
      GitCommit? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_git_info(
      GitInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_server_profile(
      ServerProfile? self, SseSerializer serializer);

  @protected
  void sse_encode_series_row(SeriesRow self, SseSerializer serializer);

  @protected
  void sse_encode_server_info(ServerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_server_profile(ServerProfile self, SseSerializer serializer);

  @protected
  void sse_encode_thumbnail_row(ThumbnailRow self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
