// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Author row shared by series/book detail reads.
class AuthorRow {
  final String name;
  final String role;

  const AuthorRow({
    required this.name,
    required this.role,
  });

  @override
  int get hashCode => name.hashCode ^ role.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthorRow &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          role == other.role;
}
