// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../model/server.dart';
import '../store.dart';
import '../store/books.dart';
import '../store/collections.dart';
import '../store/query.dart';
import '../store/readlists.dart';
import '../store/series.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Full book detail (row + metadata + tags + authors + read progress).
class BookDetailRow {
  final String serverId;
  final String remoteId;
  final String seriesId;
  final String? seriesTitle;
  final String title;
  final String? number;
  final double? numberSort;
  final String? summary;
  final String? isbn;
  final String? releaseDate;
  final String? mediaType;
  final PlatformInt64? pagesCount;
  final PlatformInt64? fileSize;
  final String? createdAt;
  final String? lastModified;
  final List<String> tags;
  final List<AuthorRow> authors;
  final PlatformInt64? progressPage;
  final bool progressCompleted;

  const BookDetailRow({
    required this.serverId,
    required this.remoteId,
    required this.seriesId,
    this.seriesTitle,
    required this.title,
    this.number,
    this.numberSort,
    this.summary,
    this.isbn,
    this.releaseDate,
    this.mediaType,
    this.pagesCount,
    this.fileSize,
    this.createdAt,
    this.lastModified,
    required this.tags,
    required this.authors,
    this.progressPage,
    required this.progressCompleted,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      remoteId.hashCode ^
      seriesId.hashCode ^
      seriesTitle.hashCode ^
      title.hashCode ^
      number.hashCode ^
      numberSort.hashCode ^
      summary.hashCode ^
      isbn.hashCode ^
      releaseDate.hashCode ^
      mediaType.hashCode ^
      pagesCount.hashCode ^
      fileSize.hashCode ^
      createdAt.hashCode ^
      lastModified.hashCode ^
      tags.hashCode ^
      authors.hashCode ^
      progressPage.hashCode ^
      progressCompleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookDetailRow &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          remoteId == other.remoteId &&
          seriesId == other.seriesId &&
          seriesTitle == other.seriesTitle &&
          title == other.title &&
          number == other.number &&
          numberSort == other.numberSort &&
          summary == other.summary &&
          isbn == other.isbn &&
          releaseDate == other.releaseDate &&
          mediaType == other.mediaType &&
          pagesCount == other.pagesCount &&
          fileSize == other.fileSize &&
          createdAt == other.createdAt &&
          lastModified == other.lastModified &&
          tags == other.tags &&
          authors == other.authors &&
          progressPage == other.progressPage &&
          progressCompleted == other.progressCompleted;
}

/// Collection detail: row + its member series (paged).
class CollectionDetailRow {
  final String remoteId;
  final String name;
  final bool ordered;
  final bool filtered;
  final String? createdDate;
  final String? lastModifiedDate;
  final SeriesPageResult members;

  const CollectionDetailRow({
    required this.remoteId,
    required this.name,
    required this.ordered,
    required this.filtered,
    this.createdDate,
    this.lastModifiedDate,
    required this.members,
  });

  @override
  int get hashCode =>
      remoteId.hashCode ^
      name.hashCode ^
      ordered.hashCode ^
      filtered.hashCode ^
      createdDate.hashCode ^
      lastModifiedDate.hashCode ^
      members.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectionDetailRow &&
          runtimeType == other.runtimeType &&
          remoteId == other.remoteId &&
          name == other.name &&
          ordered == other.ordered &&
          filtered == other.filtered &&
          createdDate == other.createdDate &&
          lastModifiedDate == other.lastModifiedDate &&
          members == other.members;
}

/// Paged collection rows + total.
class CollectionPageResult {
  final List<CollectionRow> items;
  final PlatformInt64 total;

  const CollectionPageResult({
    required this.items,
    required this.total,
  });

  @override
  int get hashCode => items.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectionPageResult &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total;
}

/// A collection that contains a series (detail screen membership chips).
class CollectionRef {
  final String remoteId;
  final String name;

  const CollectionRef({
    required this.remoteId,
    required this.name,
  });

  @override
  int get hashCode => remoteId.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectionRef &&
          runtimeType == other.runtimeType &&
          remoteId == other.remoteId &&
          name == other.name;
}

/// Outcome of the connection probe: server identity/version, remote
/// entities (libraries) and policy-derived capabilities.
class ConnectionResult {
  final ServerInfo serverInfo;

  /// `build.version` of the server (policy input).
  final String? serverVersion;
  final List<Library> libraries;

  /// e.g. `libraries:2`, `unknown-version`, `newer-than-snapshot:1.27.0`.
  final List<String> capabilities;

  const ConnectionResult({
    required this.serverInfo,
    this.serverVersion,
    required this.libraries,
    required this.capabilities,
  });

  @override
  int get hashCode =>
      serverInfo.hashCode ^
      serverVersion.hashCode ^
      libraries.hashCode ^
      capabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionResult &&
          runtimeType == other.runtimeType &&
          serverInfo == other.serverInfo &&
          serverVersion == other.serverVersion &&
          libraries == other.libraries &&
          capabilities == other.capabilities;
}

/// Distinct filter-chip options derived from the local mirror.
class FilterOptions {
  final List<String> tags;
  final List<String> genres;
  final List<String> statuses;

  const FilterOptions({
    required this.tags,
    required this.genres,
    required this.statuses,
  });

  @override
  int get hashCode => tags.hashCode ^ genres.hashCode ^ statuses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FilterOptions &&
          runtimeType == other.runtimeType &&
          tags == other.tags &&
          genres == other.genres &&
          statuses == other.statuses;
}

/// One queued client write, in the shape the UI lists it under the badge.
class OutboxEntryDto {
  final String id;
  final String entityId;
  final String mutationType;
  final PlatformInt64 retryCount;
  final String? lastError;

  /// `pending` | `failed`.
  final String state;
  final String? nextRetryAt;
  final String createdAt;

  const OutboxEntryDto({
    required this.id,
    required this.entityId,
    required this.mutationType,
    required this.retryCount,
    this.lastError,
    required this.state,
    this.nextRetryAt,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      entityId.hashCode ^
      mutationType.hashCode ^
      retryCount.hashCode ^
      lastError.hashCode ^
      state.hashCode ^
      nextRetryAt.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutboxEntryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          entityId == other.entityId &&
          mutationType == other.mutationType &&
          retryCount == other.retryCount &&
          lastError == other.lastError &&
          state == other.state &&
          nextRetryAt == other.nextRetryAt &&
          createdAt == other.createdAt;
}

/// The Outbox badge plus whatever has given up — the only part of the queue a
/// user can act on.
class OutboxStatusDto {
  final String serverId;

  /// Due right now; an upload pass would take these.
  final PlatformInt64 pending;

  /// Still waiting for a backoff deadline that is on disk, not in memory.
  final PlatformInt64 waiting;
  final PlatformInt64 failed;
  final PlatformInt64 total;
  final List<OutboxEntryDto> failedEntries;

  const OutboxStatusDto({
    required this.serverId,
    required this.pending,
    required this.waiting,
    required this.failed,
    required this.total,
    required this.failedEntries,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      pending.hashCode ^
      waiting.hashCode ^
      failed.hashCode ^
      total.hashCode ^
      failedEntries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutboxStatusDto &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          pending == other.pending &&
          waiting == other.waiting &&
          failed == other.failed &&
          total == other.total &&
          failedEntries == other.failedEntries;
}

/// Readlist detail: row + its ordered books (paged).
class ReadlistDetailRow {
  final String remoteId;
  final String name;
  final String? summary;
  final bool ordered;
  final bool filtered;
  final String? createdDate;
  final String? lastModifiedDate;
  final BookPageResult books;

  const ReadlistDetailRow({
    required this.remoteId,
    required this.name,
    this.summary,
    required this.ordered,
    required this.filtered,
    this.createdDate,
    this.lastModifiedDate,
    required this.books,
  });

  @override
  int get hashCode =>
      remoteId.hashCode ^
      name.hashCode ^
      summary.hashCode ^
      ordered.hashCode ^
      filtered.hashCode ^
      createdDate.hashCode ^
      lastModifiedDate.hashCode ^
      books.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadlistDetailRow &&
          runtimeType == other.runtimeType &&
          remoteId == other.remoteId &&
          name == other.name &&
          summary == other.summary &&
          ordered == other.ordered &&
          filtered == other.filtered &&
          createdDate == other.createdDate &&
          lastModifiedDate == other.lastModifiedDate &&
          books == other.books;
}

/// Paged readlist rows + total.
class ReadlistPageResult {
  final List<ReadlistRow> items;
  final PlatformInt64 total;

  const ReadlistPageResult({
    required this.items,
    required this.total,
  });

  @override
  int get hashCode => items.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadlistPageResult &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total;
}

/// Full series detail (row + metadata + normalized tags/genres/authors +
/// collection memberships).
class SeriesDetailRow {
  final String serverId;
  final String remoteId;
  final String libraryId;
  final String name;
  final String? sortName;
  final String? status;
  final String? createdAt;
  final String? lastModified;
  final PlatformInt64? booksCount;
  final PlatformInt64? booksReadCount;
  final PlatformInt64? booksUnreadCount;
  final PlatformInt64? booksInProgressCount;
  final String? summary;
  final String? publisher;
  final String? readingDirection;
  final String? language;
  final String? ageRating;
  final PlatformInt64? totalBookCount;
  final List<String> genres;
  final List<String> tags;
  final List<AuthorRow> authors;
  final List<CollectionRef> collections;

  const SeriesDetailRow({
    required this.serverId,
    required this.remoteId,
    required this.libraryId,
    required this.name,
    this.sortName,
    this.status,
    this.createdAt,
    this.lastModified,
    this.booksCount,
    this.booksReadCount,
    this.booksUnreadCount,
    this.booksInProgressCount,
    this.summary,
    this.publisher,
    this.readingDirection,
    this.language,
    this.ageRating,
    this.totalBookCount,
    required this.genres,
    required this.tags,
    required this.authors,
    required this.collections,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      remoteId.hashCode ^
      libraryId.hashCode ^
      name.hashCode ^
      sortName.hashCode ^
      status.hashCode ^
      createdAt.hashCode ^
      lastModified.hashCode ^
      booksCount.hashCode ^
      booksReadCount.hashCode ^
      booksUnreadCount.hashCode ^
      booksInProgressCount.hashCode ^
      summary.hashCode ^
      publisher.hashCode ^
      readingDirection.hashCode ^
      language.hashCode ^
      ageRating.hashCode ^
      totalBookCount.hashCode ^
      genres.hashCode ^
      tags.hashCode ^
      authors.hashCode ^
      collections.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeriesDetailRow &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          remoteId == other.remoteId &&
          libraryId == other.libraryId &&
          name == other.name &&
          sortName == other.sortName &&
          status == other.status &&
          createdAt == other.createdAt &&
          lastModified == other.lastModified &&
          booksCount == other.booksCount &&
          booksReadCount == other.booksReadCount &&
          booksUnreadCount == other.booksUnreadCount &&
          booksInProgressCount == other.booksInProgressCount &&
          summary == other.summary &&
          publisher == other.publisher &&
          readingDirection == other.readingDirection &&
          language == other.language &&
          ageRating == other.ageRating &&
          totalBookCount == other.totalBookCount &&
          genres == other.genres &&
          tags == other.tags &&
          authors == other.authors &&
          collections == other.collections;
}

/// What one SSE tick reported. `dirtyBooks` are the ids this tick re-fetched
/// into SQLite — the caller re-reads its list rather than applying a payload,
/// because an event is a hint, never truth.
class SsePollResult {
  /// Feed this straight back into the next `sse_poll`.
  final String stateJson;

  /// `idle` | `applied` | `reconcile` | `backing-off` | `reconcile-only`.
  final String action;

  /// True when the caller must run a Reconcile (`sse_reconnected`) and then
  /// hand the state back through `sse_reconciled`.
  final bool reconcile;
  final List<String> dirtyBooks;
  final String phase;

  /// Why the stream is parked (e.g. `/sse/v1/events` is not an event stream).
  final String? reason;

  /// Counts of the hints this tick turned into local rows.
  final PlatformInt64 booksWritten;
  final PlatformInt64 booksDeleted;

  /// False once the parked stream is not worth keeping: a closed, failed or
  /// handed-up stream owes a handshake that only the Rust side may run.
  final bool keepSocket;

  const SsePollResult({
    required this.stateJson,
    required this.action,
    required this.reconcile,
    required this.dirtyBooks,
    required this.phase,
    this.reason,
    required this.booksWritten,
    required this.booksDeleted,
    required this.keepSocket,
  });

  @override
  int get hashCode =>
      stateJson.hashCode ^
      action.hashCode ^
      reconcile.hashCode ^
      dirtyBooks.hashCode ^
      phase.hashCode ^
      reason.hashCode ^
      booksWritten.hashCode ^
      booksDeleted.hashCode ^
      keepSocket.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SsePollResult &&
          runtimeType == other.runtimeType &&
          stateJson == other.stateJson &&
          action == other.action &&
          reconcile == other.reconcile &&
          dirtyBooks == other.dirtyBooks &&
          phase == other.phase &&
          reason == other.reason &&
          booksWritten == other.booksWritten &&
          booksDeleted == other.booksDeleted &&
          keepSocket == other.keepSocket;
}

/// What one upload pass did, and the queue it left behind: the caller needs
/// both to refresh the badge without a second round trip.
class UploadOutcomeDto {
  final String serverId;
  final PlatformInt64 considered;
  final PlatformInt64 uploaded;

  /// Converged without a request (rule R3).
  final PlatformInt64 alreadyApplied;

  /// Rule R4: a strictly later remote action won.
  final PlatformInt64 remoteWins;

  /// Rule R1: the server confirmed the entity is gone.
  final PlatformInt64 gone;
  final PlatformInt64 retried;
  final PlatformInt64 rejected;
  final PlatformInt64 blockedAuthentication;

  /// `complete` | `blocked_authentication`.
  final String status;
  final OutboxStatusDto outbox;

  const UploadOutcomeDto({
    required this.serverId,
    required this.considered,
    required this.uploaded,
    required this.alreadyApplied,
    required this.remoteWins,
    required this.gone,
    required this.retried,
    required this.rejected,
    required this.blockedAuthentication,
    required this.status,
    required this.outbox,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      considered.hashCode ^
      uploaded.hashCode ^
      alreadyApplied.hashCode ^
      remoteWins.hashCode ^
      gone.hashCode ^
      retried.hashCode ^
      rejected.hashCode ^
      blockedAuthentication.hashCode ^
      status.hashCode ^
      outbox.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UploadOutcomeDto &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          considered == other.considered &&
          uploaded == other.uploaded &&
          alreadyApplied == other.alreadyApplied &&
          remoteWins == other.remoteWins &&
          gone == other.gone &&
          retried == other.retried &&
          rejected == other.rejected &&
          blockedAuthentication == other.blockedAuthentication &&
          status == other.status &&
          outbox == other.outbox;
}
