// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../model/server.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Outcome of the connection probe: server identity/version, remote
/// entities (libraries) and policy-derived capabilities.
class ConnectionResult {
  final ServerInfo serverInfo;

  /// `build.version` of the server (policy input).
  final String? serverVersion;
  final List<Library> libraries;

  /// e.g. `libraries:2`, `unknown-version`, `newer-than-snapshot:1.27.0`.
  final List<String> capabilities;

  const ConnectionResult({
    required this.serverInfo,
    this.serverVersion,
    required this.libraries,
    required this.capabilities,
  });

  @override
  int get hashCode =>
      serverInfo.hashCode ^
      serverVersion.hashCode ^
      libraries.hashCode ^
      capabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionResult &&
          runtimeType == other.runtimeType &&
          serverInfo == other.serverInfo &&
          serverVersion == other.serverVersion &&
          libraries == other.libraries &&
          capabilities == other.capabilities;
}
