// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../model/server_profile.dart';
import '../store/series.dart';
import '../sync/bootstrap.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// BootstrapSync (API Key auth) — mirrors the first page of series.
Future<BootstrapSummary> bootstrap(
        {required String dbPath,
        required String serverId,
        required String baseUrl,
        required String apiKey}) =>
    RustLib.instance.api.crateFfiBridgeBootstrap(
        dbPath: dbPath, serverId: serverId, baseUrl: baseUrl, apiKey: apiKey);

Future<void> saveServer(
        {required String dbPath, required ServerProfile profile}) =>
    RustLib.instance.api
        .crateFfiBridgeSaveServer(dbPath: dbPath, profile: profile);

Future<List<ServerProfile>> listServers({required String dbPath}) =>
    RustLib.instance.api.crateFfiBridgeListServers(dbPath: dbPath);

Future<List<SeriesRow>> fetchSeries(
        {required String dbPath,
        required String serverId,
        required PlatformInt64 limit,
        required PlatformInt64 offset}) =>
    RustLib.instance.api.crateFfiBridgeFetchSeries(
        dbPath: dbPath, serverId: serverId, limit: limit, offset: offset);
