// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// An error as the FFI boundary sees it.
class CoreError implements FrbException {
  final ErrorCode code;

  /// Human-readable, for a support export. Never a parse target: it is the
  /// `ApiError`'s own text, which is allowed to change wording freely.
  final String message;

  /// Derived from `code` at construction, so the two can never disagree.
  final bool retryable;

  /// `true` when the user must act. Also derived.
  final bool needsUser;

  const CoreError({
    required this.code,
    required this.message,
    required this.retryable,
    required this.needsUser,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      message.hashCode ^
      retryable.hashCode ^
      needsUser.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          retryable == other.retryable &&
          needsUser == other.needsUser;
}

/// What kind of failure this was. Serialized as the lowerCamelCase name, which
/// is the spelling all three platforms store in the shared fixture.
enum ErrorCode {
  /// 401 or 403: the server rejected the credential. The only code in here
  /// whose fix is something the user must type.
  authExpired,

  /// No route, refused, timed out, or a stream that stopped mid-body.
  networkUnavailable,

  /// A response that says the entity is not there (404, 410).
  notFound,

  /// The server already has a different answer for this (409).
  conflict,

  /// 429: back off and come back, on the existing schedule.
  rateLimited,

  /// A generic server-side failure (any other 4xx/5xx).
  serverError,

  /// This build's transport contract does not cover that server.
  contractUnsupported,

  /// The caller asked for something malformed, or the URL is not a URL.
  invalidInput,

  /// A response arrived and is not the shape documented at
  /// `specs/openapi/`.
  decodeFailed,

  /// SQLite said no. Retryable only through [`ErrorCode::DatabaseBusy`].
  databaseFailure,

  /// Another connection held the write lock past `busy_timeout`.
  databaseBusy,

  /// The filesystem refused a write the core had already been told to make.
  storageFailure,

  /// A bounded event-stream read saw no frame. Normal, not a failure.
  idle,

  /// Anything this build cannot name, including a code from a newer client.
  unknown,
  ;
}
